[acesso]
senha_admin = "6030"
[supabase]
url = "https://crckzznzdvsxdumqjybb.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNyY2t6em56ZHZzeGR1bXFqeWJiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA2NzU4NjUsImV4cCI6MjA4NjI1MTg2NX0.klWSnalIsbk2WVwofPtlCeExvkz2MuS150ULWQAoNqk"